import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "en" | "ar";

type Dict = Record<string, { en: string; ar: string }>;

const TRANSLATIONS: Dict = {
  // Navbar
  "nav.properties": { en: "Properties", ar: "العقارات" },
  "nav.allProperties": { en: "All Properties", ar: "جميع العقارات" },
  "nav.offPlan": { en: "Off Plan", ar: "على الخارطة" },
  "nav.sale": { en: "Sale", ar: "للبيع" },
  "nav.rent": { en: "Rent", ar: "للإيجار" },
  "nav.communities": { en: "Communities", ar: "المجتمعات" },
  "nav.investment": { en: "Investment", ar: "الاستثمار" },
  "nav.insights": { en: "Insights", ar: "رؤى" },
  "nav.agents": { en: "Agents", ar: "الوكلاء" },
  "nav.about": { en: "About", ar: "من نحن" },
  "nav.contact": { en: "Contact", ar: "اتصل بنا" },
  "nav.getInTouch": { en: "Get in Touch", ar: "تواصل معنا" },
  "nav.crm": { en: "CRM", ar: "لوحة التحكم" },
  "nav.crmLogin": { en: "Login", ar: "تسجيل الدخول" },

  // Hero
  "hero.title1": { en: "Your Key to the", ar: "مفتاحك إلى" },
  "hero.title2": { en: "UAE Skyline", ar: "أفق الإمارات" },
  "hero.subtitle": {
    en: "Ascend into Dubai & Abu Dhabi's most coveted addresses.",
    ar: "ارتقِ إلى أرقى العناوين في دبي وأبوظبي.",
  },
  "hero.searchProperties": { en: "Search Properties", ar: "ابحث عن العقارات" },
  "hero.propertyType": { en: "Property Type", ar: "نوع العقار" },
  "hero.bedrooms": { en: "Bedrooms", ar: "غرف النوم" },
  "hero.priceRange": { en: "Price Range", ar: "نطاق السعر" },
  "hero.community": { en: "Community", ar: "المجتمع" },
  "hero.buy": { en: "Buy", ar: "شراء" },
  "hero.groundFloor": { en: "Ground Floor", ar: "الطابق الأرضي" },

  // Get in Touch dialog
  "git.title": { en: "Get in Touch", ar: "تواصل معنا" },
  "git.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "git.fullNamePlaceholder": { en: "Enter Full Name", ar: "أدخل الاسم الكامل" },
  "git.email": { en: "Email Address", ar: "البريد الإلكتروني" },
  "git.emailPlaceholder": { en: "Enter your email", ar: "أدخل بريدك الإلكتروني" },
  "git.phone": { en: "Phone Number", ar: "رقم الهاتف" },
  "git.phonePlaceholder": { en: "Enter your phone number", ar: "أدخل رقم هاتفك" },
  "git.whatsapp": { en: "WhatsApp Number", ar: "رقم الواتساب" },
  "git.whatsappPlaceholder": { en: "Enter your WhatsApp number", ar: "أدخل رقم الواتساب" },
  "git.optIn": { en: "Keep me updated on news and offers", ar: "أبقني على اطلاع بالأخبار والعروض" },
  "git.privacy": {
    en: "Please review our privacy policy to understand how Your Key handles your personal data.",
    ar: "يرجى مراجعة سياسة الخصوصية لفهم كيفية تعامل Your Key مع بياناتك الشخصية.",
  },
  "git.submit": { en: "Submit", ar: "إرسال" },
  "git.sending": { en: "Sending...", ar: "جارٍ الإرسال..." },

  // FAQ
  "faq.kicker": { en: "Frequently Asked", ar: "الأسئلة" },
  "faq.kickerAccent": { en: "Questions", ar: "الشائعة" },
  "faq.subtitle": {
    en: "Everything you need to know about buying, renting, and investing in the UAE.",
    ar: "كل ما تحتاج معرفته عن الشراء والإيجار والاستثمار في الإمارات.",
  },
};

// English-source-keyed Arabic dictionary. t("English text") returns the Arabic
// translation when lang === "ar", otherwise the English source text itself.
// This lets components wrap visible copy with t("...") without inventing keys.
const AR: Record<string, string> = {
  "Property for Sale": "عقارات للبيع",
  "View all properties for sale": "عرض جميع العقارات للبيع",
  "Beds": "غرف النوم",
  "Baths": "الحمامات",
  "Square (ft)": "المساحة (قدم)",
  "Listing by": "بواسطة",
  "Rent a Property": "استئجار عقار",
  "L33 · Leasing": "الطابق 33 · التأجير",
  "View apartments for rent": "عرض الشقق للإيجار",
  "PH · Valuation": "البنتهاوس · التقييم",
  "Reviews About Our Company": "آراء عن شركتنا",
  "What is Your Property's Value?": "ما هي قيمة عقارك؟",
  "Request Property Valuation": "اطلب تقييم العقار",
  "View properties": "عرض العقارات",
  "View all projects": "عرض جميع المشاريع",
  "payment plan": "خطة سداد",
  "Download Floor Plan": "تحميل المخطط الطابقي",
  "Download Brochure PDF": "تحميل الكتيب PDF",
  "BUY": "شراء",
  "RENT": "إيجار",
  "Apartment": "شقة",
  "Villa": "فيلا",
  "Townhouse": "تاون هاوس",
  "Previous reviews": "المراجعات السابقة",
  "Next reviews": "المراجعات التالية",
  "Dubai & Abu Dhabi skyline": "أفق دبي وأبوظبي",
  "Get an accurate, data-driven valuation of your Dubai or Abu Dhabi property from our expert advisors. Understand current market demand and maximise your return whether you plan to sell or lease.":
    "احصل على تقييم دقيق ومبني على البيانات لعقارك في دبي أو أبوظبي من خبرائنا. افهم الطلب الحالي في السوق وحقق أقصى عائد سواء كنت تخطط للبيع أو التأجير.",
  "Buy": "شراء",
  "Rent": "إيجار",
  "Off-Plan": "على الخارطة",
  "Property Type": "نوع العقار",
  "Bedrooms": "غرف النوم",
  "Price Range": "نطاق السعر",
  "Community": "المجتمع",
  "Search Properties": "ابحث عن العقارات",
  "Scroll down to explore the portfolio": "انتقل للأسفل لاستكشاف المحفظة",
  "GROUND FLOOR": "الطابق الأرضي",
  "L12 · The Portfolio": "الطابق 12 · المحفظة",
  "Featured Properties": "عقارات مميزة",
  "View Portfolio": "عرض المحفظة",
  "Studio": "استوديو",
  "L24 · Rising": "الطابق 24 · المشاريع الصاعدة",
  "Towers Under Construction": "أبراج قيد الإنشاء",
  "Secure your future with Dubai & Abu Dhabi's most anticipated new developments.": "اضمن مستقبلك مع أكثر المشاريع الجديدة ترقباً في دبي وأبوظبي.",
  "View All Off-Plan": "عرض جميع عقارات الخارطة",
  "L36 · The Numbers": "الطابق 36 · الأرقام",
  "Investment Analytics": "تحليلات الاستثمار",
  "Years Experience": "سنوات الخبرة",
  "Properties Sold": "عقارات مباعة",
  "Happy Clients": "عملاء سعداء",
  "AED Transaction Value": "قيمة المعاملات بالدرهم",
  "Mortgage Tools": "أدوات الرهن العقاري",
  "Plan every financial angle of your purchase.": "خطط لكل جانب مالي من عملية شرائك.",
  "L48 · Prime Altitudes": "الطابق 48 · المواقع المرموقة",
  "Coveted Locations": "المواقع المرغوبة",
  "Property": "عقار",
  "Properties": "العقارات",
  "Explore All Communities": "استكشف جميع المجتمعات",
  "L54 · Concierge": "الطابق 54 · خدمة الكونسيرج",
  "Bespoke Services": "خدمات مخصصة",
  "Buy Property": "شراء عقار",
  "Find your dream home or next investment from our portfolio.": "اعثر على منزل أحلامك أو استثمارك القادم من محفظتنا.",
  "Sell Property": "بيع عقار",
  "Get the best market value with our expert strategies.": "احصل على أفضل قيمة سوقية من خلال استراتيجياتنا المتخصصة.",
  "Rent & Lease": "الإيجار والتأجير",
  "Discover high-quality rental properties or find reliable tenants.": "اكتشف عقارات إيجار عالية الجودة أو اعثر على مستأجرين موثوقين.",
  "Property Management": "إدارة العقارات",
  "Hassle-free management of your assets.": "إدارة أصولك دون أي عناء.",
  "Investment Advisory": "الاستشارات الاستثمارية",
  "Data-driven insights to build a profitable portfolio.": "رؤى قائمة على البيانات لبناء محفظة مربحة.",
  "Free Valuation": "تقييم مجاني",
  "Login": "تسجيل الدخول",
  "Accurate property valuations based on current data.": "تقييمات عقارية دقيقة بناءً على البيانات الحالية.",
  "CLOUD · Trust": "السحابة · الثقة",
  "What Our Clients Say": "ماذا يقول عملاؤنا",
  "Google Reviews": "تقييمات جوجل",
  "Your Key Property Management": "Your Key لإدارة العقارات",
  "Exceptional service from start to finish. They found exactly what we were looking for in Dubai Marina and handled every detail with genuine care.": "خدمة استثنائية من البداية إلى النهاية. وجدوا بالضبط ما كنا نبحث عنه في دبي مارينا وتعاملوا مع كل التفاصيل باهتمام صادق.",
  "Their market knowledge in Abu Dhabi is unmatched. They handled the sale of my villa with the utmost professionalism and complete transparency.": "معرفتهم بسوق أبوظبي لا تُضاهى. تعاملوا مع بيع فيلتي بأقصى درجات الاحترافية والشفافية الكاملة.",
  "Total peace of mind knowing my investments are in safe hands. The management team is responsive, honest, and genuinely puts clients first.": "راحة بال تامة بمعرفة أن استثماراتي في أيدٍ أمينة. فريق الإدارة سريع الاستجابة وصادق ويضع العملاء في المقام الأول حقاً.",
  "Professional, discreet, and highly effective. Acquiring our Downtown penthouse was seamless from the first viewing right through to handover.": "محترفون ومتحفظون وفعّالون للغاية. كان شراء بنتهاوس وسط المدينة سلساً من المعاينة الأولى وحتى التسليم.",
  "Best brokerage experience I have had in the UAE. They listened, advised honestly, and secured a great price. Highly recommended to anyone.": "أفضل تجربة وساطة عقارية حظيت بها في الإمارات. أنصتوا وقدّموا النصح بصدق وحصلوا على سعر ممتاز. أنصح بهم الجميع بشدة.",
  "From the first call they were attentive and knowledgeable. They found us a fantastic rental on the Palm within days. Five stars without hesitation.": "منذ المكالمة الأولى كانوا منتبهين وذوي خبرة. وجدوا لنا عقار إيجار رائعاً في النخلة خلال أيام. خمس نجوم دون تردد.",
  "Read All Reviews on Google": "اقرأ جميع التقييمات على جوجل",
  "PH · PENTHOUSE": "البنتهاوس · القمة",
  "You've reached the summit.": "لقد وصلت إلى القمة.",
  "Ready to elevate your real estate portfolio? Contact our concierge team for a private consultation.": "هل أنت مستعد للارتقاء بمحفظتك العقارية؟ تواصل مع فريق الكونسيرج لدينا لاستشارة خاصة.",
  "Your Name": "اسمك",
  "Email": "البريد الإلكتروني",
  "Request Contact": "اطلب التواصل",
  "Exclusive Portfolio": "محفظة حصرية",
  "View All Properties": "عرض جميع العقارات",
  "Signature Villa on Frond M": "فيلا مميزة على سعفة M",
  "Burj Khalifa View Penthouse": "بنتهاوس بإطلالة على برج خليفة",
  "Waterfront Duplex": "دوبلكس على الواجهة المائية",
  "Palm Jumeirah": "نخلة جميرا",
  "Downtown Dubai": "وسط مدينة دبي",
  "Dubai Marina": "مرسى دبي",
  "sqft": "قدم مربع",
  "Our Expertise": "خبرتنا",
  "Comprehensive Real Estate Solutions": "حلول عقارية شاملة",
  "From strategic acquisitions to meticulous property management, we provide a holistic approach to luxury real estate in the UAE.": "من عمليات الاستحواذ الاستراتيجية إلى الإدارة الدقيقة للعقارات، نقدم نهجاً متكاملاً للعقارات الفاخرة في الإمارات.",
  "Buying": "الشراء",
  "Access off-market listings and premium developments. We guide you through seamless acquisitions.": "احصل على عقارات خارج السوق ومشاريع راقية. نرشدك خلال عمليات استحواذ سلسة.",
  "Selling": "البيع",
  "Position your property to the right audience with our global network of high-net-worth investors.": "اعرض عقارك على الجمهور المناسب من خلال شبكتنا العالمية من المستثمرين أصحاب الثروات العالية.",
  "Renting": "الإيجار",
  "Find the perfect long-term luxury residence or lease your property to verified corporate tenants.": "اعثر على المسكن الفاخر المثالي طويل الأمد أو أجّر عقارك لمستأجرين من الشركات الموثوقة.",
  "End-to-end management ensuring your asset is maintained to pristine standards.": "إدارة متكاملة تضمن الحفاظ على أصلك وفق أرقى المعايير.",
  "Data-driven insights to maximize yields in Dubai's rapidly evolving real estate market.": "رؤى قائمة على البيانات لتعظيم العوائد في سوق دبي العقاري سريع التطور.",
  "Client Perspectives": "آراء العملاء",
  "Their understanding of the Dubai luxury market is unparalleled. They found us an off-market villa on the Palm that perfectly matched our exacting requirements.": "فهمهم لسوق دبي الفاخر لا مثيل له. وجدوا لنا فيلا خارج السوق في النخلة تطابقت تماماً مع متطلباتنا الدقيقة.",
  "International Investor": "مستثمر دولي",
  "Professional, discreet, and highly effective. The entire process of acquiring our penthouse in Downtown Dubai was handled with absolute precision.": "محترفون ومتحفظون وفعّالون للغاية. تمت إدارة عملية شراء البنتهاوس في وسط مدينة دبي بأكملها بدقة مطلقة.",
  "Expat Resident": "مقيم وافد",
  "Your Key has managed my property portfolio for three years. Their attention to detail and tenant curation is the best I have experienced in the region.": "تولّت Your Key إدارة محفظتي العقارية لمدة ثلاث سنوات. اهتمامهم بالتفاصيل واختيارهم للمستأجرين هو الأفضل الذي اختبرته في المنطقة.",
  "Portfolio Owner": "مالك محفظة",
  "FOR SALE": "للبيع",
  "FOR RENT": "للإيجار",
  "OFF PLAN": "على الخارطة",
  "View Details": "عرض التفاصيل",
  "Coveted Location": "موقع مرموق",
  "Portfolio": "المحفظة",
  "Elevated Living": "حياة مرتفعة",
  "View all locations": "عرض جميع المواقع",
  "All Types": "جميع الأنواع",
  "All Communities": "جميع المجتمعات",
  "Any Bedrooms": "أي عدد من الغرف",
  "Any Price": "أي سعر",
  "Apartments": "شقق",
  "Villas": "فلل",
  "Townhouses": "بيوت متلاصقة",
  "Penthouse": "بنتهاوس",
  "Commercial": "تجاري",
  "Any Location": "أي موقع",
  "Dubai": "دبي",
  "Abu Dhabi": "أبوظبي",
  "Saadiyat Island": "جزيرة السعديات",
  "Beds (Any)": "غرف النوم (أي)",
  "1 Bed": "غرفة نوم واحدة",
  "2 Beds": "غرفتا نوم",
  "3+ Beds": "3 غرف نوم أو أكثر",
  "Refine Search": "تنقيح البحث",
  "Status": "الحالة",
  "Showing": "عرض",
  "results": "نتائج",
  "No properties match your altitude": "لا توجد عقارات تطابق بحثك",
  "Reset Console": "إعادة تعيين عوامل التصفية",
  "Enquiry sent. The agent will contact you shortly.": "تم إرسال الاستفسار. سيتواصل معك الوكيل قريبًا.",
  "Could not send your enquiry. Please try again.": "تعذّر إرسال استفسارك. يرجى المحاولة مرة أخرى.",
  "Property Not Found": "العقار غير موجود",
  "Back to Portfolio": "العودة إلى المحفظة",
  "Type": "النوع",
  "Bathrooms": "الحمامات",
  "Area": "المساحة",
  "About this Property": "عن هذا العقار",
  "Amenities": "المرافق",
  "Listed By": "مدرج بواسطة",
  "Call": "اتصل",
  "WhatsApp": "واتساب",
  "Email Agent": "راسل الوكيل",
  "Please enter your name and contact": "يرجى إدخال اسمك ووسيلة التواصل",
  "Request a viewing": "اطلب معاينة",
  "Your name": "اسمك",
  "Email or phone": "البريد الإلكتروني أو الهاتف",
  "Sending...": "جارٍ الإرسال...",
  "Send Enquiry": "إرسال الاستفسار",
  "Similar Altitudes": "عقارات مشابهة",
  "Future Altitudes": "آفاق مستقبلية",
  "Off-Plan Properties": "عقارات على الخارطة",
  "Towers under construction in Dubai & Abu Dhabi": "أبراج قيد الإنشاء في دبي وأبوظبي",
  "All Projects": "جميع المشاريع",
  "project": "مشروع",
  "projects": "مشاريع",
  "Saved Altitudes": "المحفوظات",
  "Your Portfolio": "محفظتك",
  "You haven't saved any properties yet": "لم تقم بحفظ أي عقارات بعد",
  "Browse our portfolio and click the heart icon to save them here.": "تصفح محفظتنا وانقر على أيقونة القلب لحفظها هنا.",
  "Explore Altitudes": "استكشف العقارات",
  "Prime Altitudes": "المرتفعات المميزة",
  "Explore UAE Communities": "استكشف مجتمعات الإمارات",
  "Discover the perfect neighborhood for your lifestyle": "اكتشف الحي المثالي لأسلوب حياتك",
  "All Elevations": "جميع المستويات",
  "Avg Buy": "متوسط سعر الشراء",
  "Avg Rent": "متوسط الإيجار",
  "yr": "سنة",
  "2 weeks ago": "قبل أسبوعين",
  "1 month ago": "قبل شهر",
  "2 months ago": "قبل شهرين",
  "3 months ago": "قبل 3 أشهر",
  "Types:": "الأنواع:",
  "Glass Facade": "واجهة زجاجية",
  "Our Story": "قصتنا",
  "Ascending Together": "نرتقي معًا",
  "Your Key Property Management is your dedicated partner in navigating the dynamic UAE property market.": "Your Key لإدارة العقارات هي شريكك المخصص في التنقل ضمن سوق العقارات الديناميكي في الإمارات.",
  "Foundation": "الأساس",
  "Established with Vision": "تأسست برؤية",
  "Founded over 15 years ago, Your Key Property Management has grown from a boutique agency into one of the most respected and trusted real estate brokerages in the United Arab Emirates.": "تأسست Your Key لإدارة العقارات قبل أكثر من 15 عامًا، ونمت من وكالة صغيرة متخصصة لتصبح واحدة من أكثر شركات الوساطة العقارية احترامًا وموثوقية في دولة الإمارات العربية المتحدة.",
  "Operating across Abu Dhabi and Dubai, we bridge the gap between premium properties and discerning clients. Whether you are a first-time buyer, a seasoned investor, or looking for comprehensive property management, we deliver transparent, professional, and personalized service.": "نعمل في أبوظبي ودبي، ونسد الفجوة بين العقارات الفاخرة والعملاء المميزين. سواء كنت مشتريًا لأول مرة، أو مستثمرًا متمرسًا، أو تبحث عن إدارة عقارية شاملة، فإننا نقدم خدمة شفافة ومهنية ومخصصة.",
  "Our Mission": "مهمتنا",
  "To provide unparalleled real estate services through transparency, expertise, and a deep understanding of our clients' needs.": "تقديم خدمات عقارية لا مثيل لها من خلال الشفافية والخبرة والفهم العميق لاحتياجات عملائنا.",
  "Our Vision": "رؤيتنا",
  "To be the undisputed leader in UAE real estate, recognized for our integrity, innovation, and exceptional results.": "أن نكون الرائد بلا منازع في القطاع العقاري في الإمارات، معروفين بنزاهتنا وابتكارنا ونتائجنا الاستثنائية.",
  "The Experts": "الخبراء",
  "Meet The Team": "تعرّف على الفريق",
  "Our team will be available shortly.": "سيكون فريقنا متاحاً قريباً.",
  "Enquiry sent. Our team will be in touch shortly.": "تم إرسال الاستفسار. سيتواصل معك فريقنا قريبًا.",
  "Please enter your name": "يرجى إدخال اسمك",
  "Please provide an email or phone number": "يرجى تقديم بريد إلكتروني أو رقم هاتف",
  "Reach Out": "تواصل معنا",
  "Contact Us": "تواصل معنا",
  "Send an Enquiry": "أرسل استفسارًا",
  "Full Name": "الاسم الكامل",
  "Email Address": "البريد الإلكتروني",
  "Phone Number": "رقم الهاتف",
  "Message": "الرسالة",
  "Submit Enquiry": "إرسال الاستفسار",
  "Our Offices": "مكاتبنا",
  "Dubai Office": "مكتب دبي",
  "Office 17, 35th Floor, Al Saqr Business Tower,": "مكتب 17، الطابق 35، برج الصقر التجاري،",
  "DIFC, Dubai, United Arab Emirates": "مركز دبي المالي العالمي، دبي، الإمارات العربية المتحدة",
  "Abu Dhabi Office": "مكتب أبوظبي",
  "Office M01, Al Mansouri Building, Al Gheel Street,": "مكتب M01، مبنى المنصوري، شارع الغيل،",
  "Al Danah, Abu Dhabi, United Arab Emirates": "الدانة، أبوظبي، الإمارات العربية المتحدة",
  "A dedicated team of specialists guiding you through every step of buying, selling, renting, and investing across Dubai & Abu Dhabi.": "فريق متخصص ومتفانٍ يرشدك في كل خطوة من خطوات الشراء والبيع والإيجار والاستثمار في دبي وأبوظبي.",
  "Property Consultant": "مستشار عقاري",
  "Back to team": "العودة إلى الفريق",
  "Agent not found": "الوكيل غير موجود",
  "View the team": "عرض الفريق",
  "Listings by": "عقارات بواسطة",
  "property": "عقار",
  "properties": "عقارات",
  "No active listings for this agent yet.": "لا توجد عقارات نشطة لهذا الوكيل حتى الآن.",
  "Investment Tools": "أدوات الاستثمار",
  "Data-driven insights to model your returns from altitude. Visualize equity growth, rental yields, and overall profitability.": "رؤى قائمة على البيانات لنمذجة عوائدك من الأعالي. تصوّر نمو حقوق الملكية وعوائد الإيجار والربحية الإجمالية.",
  "Mortgage Calculator": "حاسبة الرهن العقاري",
  "Plan your property purchase with our comprehensive UAE mortgage calculator.": "خطط لشراء عقارك باستخدام حاسبة الرهن العقاري الشاملة في الإمارات.",
  "Insights": "رؤى",
  "Market Intelligence": "ذكاء السوق",
  "Perspectives on the Dubai and Abu Dhabi property markets — trends, neighbourhood guides, and investment strategy from our advisors.": "رؤى حول أسواق العقارات في دبي وأبوظبي — الاتجاهات وأدلة الأحياء واستراتيجية الاستثمار من مستشارينا.",
  "No articles published yet. Check back soon.": "لم تُنشر أي مقالات بعد. تحقق مرة أخرى قريبًا.",
  "Read article": "اقرأ المقال",
  "Article Not Found": "المقال غير موجود",
  "Back to Insights": "العودة إلى الرؤى",
  "All Insights": "جميع الرؤى",
  "min read": "دقيقة للقراءة",
  "More insights": "المزيد من الرؤى",
  "Your Key to UAE Real Estate. Abu Dhabi & Dubai's trusted property experts for buying, selling, renting, and investing.": "مفتاحك إلى عقارات الإمارات. خبراء العقارات الموثوقون في أبوظبي ودبي للشراء والبيع والإيجار والاستثمار.",
  "Quick Links": "روابط سريعة",
  "Communities": "المجتمعات",
  "Investment ROI": "عائد الاستثمار",
  "Agents": "الوكلاء",
  "About Us": "من نحن",
  "Contact": "اتصل بنا",
  "Our Services": "خدماتنا",
  "What We Offer": "ما نقدمه",
  "No communities listed yet for this emirate.": "لا توجد مجتمعات مدرجة بعد لهذه الإمارة.",
  "Contact Info": "معلومات الاتصال",
  "Office 17, 35th Floor, Al Saqr Business Tower, DIFC, Dubai": "مكتب 17، الطابق 35، برج الصقر التجاري، مركز دبي المالي العالمي، دبي",
  "Office M01, Al Mansouri Building, Al Gheel St, Al Danah, Abu Dhabi": "مكتب M01، مبنى المنصوري، شارع الغيل، الدانة، أبوظبي",
  "Your Key Property Management. All rights reserved.": "Your Key لإدارة العقارات. جميع الحقوق محفوظة.",
  "Licensed Real Estate Brokerage": "وساطة عقارية مرخصة",
  "Property Price": "سعر العقار",
  "Down Payment": "الدفعة المقدمة",
  "Interest Rate": "معدل الفائدة",
  "Loan Period": "مدة القرض",
  "yrs": "سنوات",
  "Total Interest": "إجمالي الفائدة",
  "Loan": "القرض",
  "Monthly Payment": "القسط الشهري",
  "Total Loan Amount": "إجمالي مبلغ القرض",
  "View Units": "عرض الوحدات",
  "Get Pre-Approval": "احصل على موافقة مبدئية",
  "Loan Amount": "مبلغ القرض",
  "Total Interest Paid": "إجمالي الفائدة المدفوعة",
  "Total Repayment": "إجمالي السداد",
  "Balance & Equity Over Time": "الرصيد وحقوق الملكية بمرور الوقت",
  "Equity (Principal Paid)": "حقوق الملكية (أصل القرض المدفوع)",
  "Outstanding Balance": "الرصيد المتبقي",
  "Outstanding Balance ": "الرصيد المتبقي",
  "Current Rate": "المعدل الحالي",
  "New Rate": "المعدل الجديد",
  "Remaining Period": "المدة المتبقية",
  "Current Monthly": "القسط الشهري الحالي",
  "New Monthly": "القسط الشهري الجديد",
  "Estimated Lifetime Saving": "التوفير الإجمالي المقدّر",
  "saved every month": "موفّرة كل شهر",
  "Refinancing increases your payment": "إعادة التمويل تزيد من قسطك",
  "Annual Rent": "الإيجار السنوي",
  "Appreciation": "معدل النمو",
  "Horizon": "الأفق الزمني",
  "Verdict": "الخلاصة",
  "Buying wins long-term": "الشراء أفضل على المدى الطويل",
  "Renting is cheaper here": "الإيجار أرخص في هذه الحالة",
  "Net Cost of Buying vs Renting": "صافي تكلفة الشراء مقابل الإيجار",
  "Net Cost — Buy": "صافي التكلفة — الشراء",
  "Cumulative Rent": "الإيجار التراكمي",
  "Monthly Income": "الدخل الشهري",
  "Monthly Debts": "الالتزامات الشهرية",
  "Savings for Down Payment": "مدخرات الدفعة المقدمة",
  "You Can Afford Up To": "يمكنك تحمّل ما يصل إلى",
  "Max Loan": "الحد الأقصى للقرض",
  "Max Monthly": "الحد الأقصى للقسط الشهري",
  "Financed": "المموّل",
  "Investment ROI Visualizer": "أداة تصوّر عائد الاستثمار",
  "Every tool to model your returns and plan your purchase.": "كل أداة لنمذجة عوائدك والتخطيط لعملية الشراء.",
  "Model your returns from altitude.": "تصوّر عوائدك من الأعالي.",
  "Area Preset": "إعداد المنطقة",
  "Rental Yield": "عائد الإيجار",
  "Capital Appreciation": "نمو رأس المال",
  "Service Charge & Costs": "رسوم الخدمة والتكاليف",
  "Holding Period (Years)": "مدة الاحتفاظ (سنوات)",
  "Total ROI": "إجمالي عائد الاستثمار",
  "Gross Yield": "العائد الإجمالي",
  "Net Yield": "العائد الصافي",
  "Cash on Cash": "العائد النقدي على النقد",
  "Break-Even": "نقطة التعادل",
  "Year": "السنة",
  "Projected Exit Value": "القيمة المتوقعة عند البيع",
  "Total Net Profit": "إجمالي صافي الربح",
  "Projected Value & Equity": "القيمة المتوقعة وحقوق الملكية",
  "Property Value": "قيمة العقار",
  "Total Equity": "إجمالي حقوق الملكية",
  "Cumulative Rent vs Costs": "الإيجار التراكمي مقابل التكاليف",
  "Cumulative Costs": "التكاليف التراكمية",
  "L30 · Signature Projects": "L30 · مشاريع مميزة",
  "Off-Plan Projects": "مشاريع على الخارطة",
  "Explore the UAE's most anticipated new developments, handpicked by Your Key.":
    "اكتشف أكثر المشاريع الجديدة المنتظرة في الإمارات، مختارة بعناية من Your Key.",
  "Starting From": "تبدأ من",
  "Handover": "التسليم",
  "Payment Plan": "خطة الدفع",
  "Explore More": "اكتشف المزيد",
  "Previous project": "المشروع السابق",
  "Next project": "المشروع التالي",
  "Unit Types": "أنواع الوحدات",
  "Project Not Found": "المشروع غير موجود",
  "All Off-Plan": "كل المشاريع على الخارطة",
  "About the Project": "عن المشروع",
  "Project Highlights": "أبرز ميزات المشروع",
  "Gallery": "معرض الصور",
  "Register Your Interest": "سجّل اهتمامك",
  "Request the brochure, pricing and payment plan for this project.":
    "اطلب الكتيب والأسعار وخطة الدفع لهذا المشروع.",
  "Phone": "الهاتف",
  "Enquire Now": "استفسر الآن",
  "Download Brochure": "تحميل الكتيب",
  "Unit Type": "نوع الوحدة",
  "Property Types & Floor Plans": "أنواع العقارات والمخططات",
  "Layout": "المخطط",
  "Size": "المساحة",
  "Enquire": "استفسر",
  "from": "من",
  "Attractive Payment Plan": "خطة دفع مميزة",
  "Get a Free Consultation": "احصل على استشارة مجانية",
  "Get a free consultation from our sales team":
    "احصل على استشارة مجانية من فريق المبيعات",
  "Location": "الموقع",
  "Project Materials": "مواد المشروع",
  "Get the full project brochure with floor plans and pricing.":
    "احصل على كتيب المشروع الكامل مع المخططات والأسعار."
};

interface LanguageContextType {
  lang: Lang;
  dir: "ltr" | "rtl";
  setLang: (l: Lang) => void;
  t: (key: keyof typeof TRANSLATIONS | string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const saved = localStorage.getItem("app_lang") as Lang | null;
    if (saved === "en" || saved === "ar") {
      setLangState(saved);
    }
  }, []);

  useEffect(() => {
    const dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang]);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("app_lang", l);
  };

  const t = (key: string) => {
    const entry = TRANSLATIONS[key];
    if (entry) return entry[lang];
    if (lang === "en") return key;
    return AR[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, dir: lang === "ar" ? "rtl" : "ltr", setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
